/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zInterfaz;

import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 *
 * @author Ramonella
 */
public class Opciones extends javax.swing.JFrame {
    
    public static Pagina paginaActual;

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        
        initComponents();
        paginaActual = new Pagina(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setTitle("Visualizar Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    
    public void setPagina(Pagina p){
        paginaActual = p;
    }
    
    
    public void cargarValores(){
        
        String cadenaSalida = paginaActual.obtenerCadenaSalida();
        String errores= paginaActual.obtenerErrores();
        String [] cadenaHTML= paginaActual.obtenerCodigoHTML();
        List<String[]> codigoJS = paginaActual.obtenerCodigoJS();
        List<String[]> codigoCss= paginaActual.obtenerCodigoCSS();
        JTextPane salida = new JTextPane();
        salida.setEditable(false);
        salida.setText(cadenaSalida);
        jTabbedPane1.add("Salida ",new JScrollPane(salida));

        JTextPane errore = new JTextPane();
        errore.setEditable(false);
        errore.setContentType("text/html");
        errore.setText(errores);
        jTabbedPane1.add("Errores ",new JScrollPane(errore));
        
        JTextPane codHTML = new JTextPane();
        codHTML.setEditable(false);
        codHTML.setText(cadenaHTML[1]);
        jTabbedPane1.add(cadenaHTML[0],new JScrollPane(codHTML));
        
        String[]temp;
        for (int i = 0; i < codigoJS.size(); i++) {
            temp= codigoJS.get(i);
            codHTML = new JTextPane();
        codHTML.setEditable(false);
        codHTML.setText(temp[1]);
        jTabbedPane1.add(temp[0],new JScrollPane(codHTML));
            
        }
        
            
          for (int i = 0; i < codigoCss.size(); i++) {
            temp= codigoCss.get(i);
            codHTML = new JTextPane();
        codHTML.setEditable(false);
        codHTML.setText(temp[1]);
        jTabbedPane1.add(temp[0],new JScrollPane(codHTML));
            
        }
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
