
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 08 12:05:44 CST 2018
//----------------------------------------------------

package proyecto1_201122872.AnalizadorExtra;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int corchetecierra = 5;
  public static final int mayuscula = 37;
  public static final int tamtext = 17;
  public static final int opaque = 41;
  public static final int negrilla = 35;
  public static final int terminalID = 3;
  public static final int coma = 25;
  public static final int derecha = 32;
  public static final int igual = 12;
  public static final int letra = 16;
  public static final int ptcoma = 9;
  public static final int men = 28;
  public static final int autoredimension = 19;
  public static final int parabre = 7;
  public static final int grupo = 6;
  public static final int alineado = 10;
  public static final int dospts = 11;
  public static final int numero = 24;
  public static final int justificado = 34;
  public static final int vertical = 21;
  public static final int visible = 22;
  public static final int EOF = 0;
  public static final int corcheteabre = 4;
  public static final int mas = 27;
  public static final int error = 1;
  public static final int fondoelemento = 18;
  public static final int horizontal = 20;
  public static final int por = 29;
  public static final int minuscula = 38;
  public static final int id = 2;
  public static final int colortext = 26;
  public static final int centrado = 33;
  public static final int texto = 13;
  public static final int izquierda = 31;
  public static final int booleano = 40;
  public static final int formato = 15;
  public static final int borde = 23;
  public static final int div = 30;
  public static final int cursiva = 36;
  public static final int capitalt = 39;
  public static final int parcierra = 8;
  public static final int cadena = 14;
}

