/* The following code was generated by JFlex 1.4.3 on 2/18/18 11:50 PM */


/* ------------------------==: CODIGO DE USUARIO :==--------------------------*/

package proyecto1_201122872.AnalizadorCJS;
    

import java_cup.runtime.Symbol;
import java.io.*;
import java.lang.*;
import java.util.ArrayList;
import java.util.LinkedList;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2/18/18 11:50 PM from the specification file
 * <tt>ScannerJS.jflex</tt>
 */
public class scannerCJS implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\57\1\30\1\0\2\57\22\0\1\57\1\54\1\4\1\27"+
    "\1\0\1\52\1\55\1\5\1\35\1\36\1\50\1\47\1\43\1\25"+
    "\1\2\1\24\12\1\1\37\1\40\1\23\1\53\1\26\2\0\1\6"+
    "\1\45\1\13\1\16\1\10\1\42\1\3\1\3\1\15\1\44\1\3"+
    "\1\22\1\31\1\14\1\12\1\21\1\46\1\17\1\41\1\7\1\20"+
    "\1\32\1\3\1\11\2\3\3\0\1\51\1\3\1\0\1\6\1\45"+
    "\1\13\1\16\1\10\1\42\1\3\1\3\1\15\1\44\1\3\1\22"+
    "\1\31\1\14\1\12\1\21\1\46\1\17\1\41\1\7\1\20\1\32"+
    "\1\3\1\11\2\3\1\33\1\56\1\34\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\10\4"+
    "\1\6\1\7\1\10\1\11\1\1\1\12\2\4\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\2\4\1\21\1\22"+
    "\1\23\1\24\1\25\1\1\1\26\2\1\1\0\1\4"+
    "\2\0\1\27\14\4\1\0\1\30\1\31\1\32\1\33"+
    "\5\4\1\34\2\4\1\35\1\36\1\37\1\40\1\41"+
    "\1\2\2\0\16\4\1\0\11\4\1\0\3\4\1\42"+
    "\6\4\1\43\1\4\1\44\1\4\1\0\6\4\1\45"+
    "\2\4\1\0\12\4\1\46\1\0\6\4\1\47\1\4"+
    "\1\0\1\50\2\4\1\51\6\4\1\0\7\4\1\0"+
    "\1\52\3\4\1\53\1\54\2\4\1\0\1\55\5\4"+
    "\1\56\1\57\2\4\1\60\1\4\1\61\1\62\1\4"+
    "\1\63\4\4\1\64\1\65\1\4\1\66\2\4\1\67"+
    "\1\70\1\4\1\71\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\60\0\220\0\300\0\60\0\360"+
    "\0\u0120\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270"+
    "\0\60\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\60"+
    "\0\60\0\60\0\60\0\60\0\60\0\u03c0\0\u03f0\0\60"+
    "\0\u0420\0\60\0\60\0\60\0\u0450\0\u0480\0\u04b0\0\u04e0"+
    "\0\u0510\0\u0540\0\u0570\0\300\0\60\0\u05a0\0\u05d0\0\u0600"+
    "\0\u0630\0\u0660\0\u0690\0\u06c0\0\u06f0\0\u0720\0\u0750\0\u0780"+
    "\0\u07b0\0\u07e0\0\60\0\60\0\60\0\u0810\0\u0840\0\u0870"+
    "\0\u08a0\0\u08d0\0\u0900\0\u0930\0\u0960\0\u0990\0\60\0\60"+
    "\0\60\0\60\0\60\0\u0510\0\u09c0\0\u09f0\0\u0a20\0\u0a50"+
    "\0\u0a80\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\u0bd0"+
    "\0\u0c00\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50"+
    "\0\u0d80\0\u0db0\0\u0de0\0\u0e10\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0"+
    "\0\u0f00\0\u0f30\0\220\0\u0f60\0\u0f90\0\u0fc0\0\u0ff0\0\u1020"+
    "\0\u1050\0\220\0\u1080\0\220\0\u10b0\0\u10e0\0\u1110\0\u1140"+
    "\0\u1170\0\u11a0\0\u11d0\0\u1200\0\220\0\u1230\0\u1260\0\u1290"+
    "\0\u12c0\0\u12f0\0\u1320\0\u1350\0\u1380\0\u13b0\0\u13e0\0\u1410"+
    "\0\u1440\0\u1470\0\220\0\u14a0\0\u14d0\0\u1500\0\u1530\0\u1560"+
    "\0\u1590\0\u15c0\0\220\0\u15f0\0\u1620\0\220\0\u1650\0\u1680"+
    "\0\220\0\u16b0\0\u16e0\0\u1710\0\u1740\0\u1770\0\u17a0\0\u17d0"+
    "\0\u1800\0\u1830\0\u1860\0\u1890\0\u18c0\0\u18f0\0\u1920\0\u1950"+
    "\0\220\0\u1980\0\u19b0\0\u19e0\0\220\0\220\0\u1a10\0\u1a40"+
    "\0\u1a70\0\220\0\u1aa0\0\u1ad0\0\u1b00\0\u1b30\0\u1b60\0\220"+
    "\0\60\0\u1b90\0\u1bc0\0\220\0\u1bf0\0\220\0\60\0\u1c20"+
    "\0\220\0\u1c50\0\u1c80\0\u1cb0\0\u1ce0\0\220\0\220\0\u1d10"+
    "\0\220\0\u1d40\0\u1d70\0\220\0\220\0\u1da0\0\220\0\220";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\3\5"+
    "\1\11\1\12\1\5\1\13\1\14\1\15\1\5\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\3\5\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\25\61\0\1\3\1\51\56\0"+
    "\1\52\1\53\1\5\2\0\15\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\11\0\4\54\1\55\53\54\1\0"+
    "\1\52\1\53\1\5\2\0\1\5\1\56\13\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\15\5\6\0\2\5\6\0\2\5\1\0"+
    "\1\5\1\57\1\5\12\0\1\52\1\53\1\5\2\0"+
    "\1\60\3\5\1\61\7\5\1\62\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\15\5\6\0\1\63\1\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\2\5\1\64\1\5"+
    "\1\65\2\5\1\66\5\5\6\0\2\5\6\0\2\5"+
    "\1\0\3\5\12\0\1\52\1\53\1\5\2\0\2\5"+
    "\1\67\12\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\1\70\14\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\7\5\1\71\5\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\35\0\1\72\26\0\1\73\31\0"+
    "\1\74\105\0\1\75\30\0\1\76\63\0\1\25\26\0"+
    "\1\25\1\0\1\52\1\53\1\5\2\0\2\5\1\77"+
    "\1\5\1\100\2\5\1\101\5\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\2\5\1\102\12\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\2\5\1\103"+
    "\4\5\1\104\5\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\1\105\11\5"+
    "\1\106\2\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\60\0\1\107\63\0\1\110\57\0\1\111\61\0\1\112"+
    "\60\0\1\113\2\0\1\114\57\0\1\52\1\115\1\5"+
    "\2\0\15\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\17\0\1\116\52\0\1\52\1\53\1\5\2\0\2\5"+
    "\1\117\12\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\1\5\1\120\13\5"+
    "\6\0\2\5\6\0\1\121\1\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\15\5\6\0\2\5\6\0"+
    "\1\122\1\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\6\5\1\123\6\5\6\0\2\5\6\0\2\5"+
    "\1\0\3\5\12\0\1\52\1\53\1\5\2\0\7\5"+
    "\1\124\5\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\13\5\1\125\1\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\1\5\1\126\13\5\6\0\2\5"+
    "\6\0\1\5\1\127\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\5\5\1\130\7\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\15\5\6\0\1\131\1\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\1\5\1\132\13\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\11\5\1\133\3\5\6\0\2\5"+
    "\6\0\2\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\15\5\6\0\2\5\6\0\1\134\1\5\1\0"+
    "\3\5\35\0\1\135\33\0\30\76\1\0\27\76\1\0"+
    "\1\52\1\53\1\5\2\0\6\5\1\136\6\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\10\5\1\137\4\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\2\5\1\140\12\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\11\5\1\141"+
    "\3\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\1\5\1\142\12\5\1\143"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\6\5\1\144\6\5\6\0\2\5"+
    "\6\0\2\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\14\5\1\145\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\6\5\1\146"+
    "\6\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\5\4\0\1\116\60\0\1\147\51\0\1\52\1\53"+
    "\1\5\2\0\3\5\1\150\11\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\2\5\1\151\12\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\2\5\1\152"+
    "\12\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\4\5\1\153\10\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\1\5\1\154\13\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\15\5\6\0\2\5\6\0\2\5\1\0\2\5\1\155"+
    "\12\0\1\52\1\53\1\5\2\0\11\5\1\156\3\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\2\5\1\157\12\5\6\0\2\5"+
    "\6\0\2\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\2\5\1\160\12\5\6\0\2\5\6\0\2\5"+
    "\1\0\3\5\12\0\1\52\1\53\1\5\2\0\12\5"+
    "\1\161\2\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\15\5\6\0\1\5"+
    "\1\162\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\4\5\1\163\10\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\1\164\14\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\1\5\1\165\13\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\36\0\1\166"+
    "\33\0\1\52\1\53\1\5\2\0\15\5\6\0\2\5"+
    "\6\0\1\167\1\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\7\5\1\170\5\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\6\5\1\171\6\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\10\5\1\172"+
    "\4\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\2\5\1\173\12\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\2\5\1\174\12\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\4\5\1\175\10\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\15\5\6\0"+
    "\2\5\6\0\1\176\1\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\5\5\1\177\7\5\6\0\2\5"+
    "\6\0\2\5\1\0\3\5\21\0\1\200\50\0\1\52"+
    "\1\53\1\5\2\0\1\5\1\201\13\5\6\0\2\5"+
    "\6\0\2\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\6\5\1\202\6\5\6\0\2\5\6\0\2\5"+
    "\1\0\3\5\12\0\1\52\1\53\1\5\2\0\11\5"+
    "\1\203\3\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\2\5\1\204\12\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\12\5\1\205\2\5\6\0\2\5"+
    "\6\0\2\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\7\5\1\206\5\5\6\0\2\5\6\0\2\5"+
    "\1\0\3\5\12\0\1\52\1\53\1\5\2\0\6\5"+
    "\1\207\6\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\5\5\1\210\7\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\15\5\6\0\1\211\1\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\11\5\1\212\3\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\4\5\1\213"+
    "\10\5\6\0\2\5\6\0\2\5\1\0\3\5\11\0"+
    "\25\166\1\214\32\166\1\0\1\52\1\53\1\5\2\0"+
    "\1\215\14\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\15\5\6\0\2\5"+
    "\6\0\1\5\1\216\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\1\5\1\217\13\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\1\220\14\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\14\5\1\221\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\5\5\1\222\7\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\4\5\1\223\10\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\7\5\1\224"+
    "\5\5\6\0\2\5\6\0\2\5\1\0\3\5\22\0"+
    "\1\225\47\0\1\52\1\53\1\5\2\0\4\5\1\226"+
    "\10\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\2\5\1\227\12\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\15\5\6\0\1\5\1\230\6\0\2\5"+
    "\1\0\3\5\12\0\1\52\1\53\1\5\2\0\4\5"+
    "\1\231\10\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\2\5\1\232\12\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\15\5\6\0\1\233\1\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\2\5\1\234\12\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\1\5\1\235"+
    "\13\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\2\5\1\236\12\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\6\5\1\237\6\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\11\0\24\166\1\240\1\214\32\166"+
    "\1\0\1\52\1\53\1\5\2\0\15\5\6\0\2\5"+
    "\6\0\2\5\1\0\1\241\2\5\12\0\1\52\1\53"+
    "\1\5\2\0\7\5\1\242\5\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\11\5\1\243\3\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\10\5\1\244"+
    "\4\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\2\5\1\245\12\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\5\5\1\246\7\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\4\5\1\247\10\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\20\0\1\250\51\0\1\52\1\53\1\5\2\0"+
    "\11\5\1\251\3\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\1\252\14\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\1\253\14\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\7\5\1\254\5\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\11\5\1\255"+
    "\3\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\4\5\1\256\10\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\6\5\1\257\6\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\1\260\14\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\11\0\24\166\1\261\1\214\32\166\1\0\1\52\1\53"+
    "\1\5\2\0\2\5\1\262\12\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\5\5\1\263\7\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\1\264\14\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\2\5\1\265\12\5\6\0\2\5"+
    "\6\0\2\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\15\5\6\0\1\266\1\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\7\5\1\267"+
    "\5\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\6\5\1\270\6\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\23\0\1\271\46\0"+
    "\1\52\1\53\1\5\2\0\10\5\1\272\4\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\12\0\1\52\1\53"+
    "\1\5\2\0\10\5\1\273\4\5\6\0\2\5\6\0"+
    "\2\5\1\0\3\5\12\0\1\52\1\53\1\5\2\0"+
    "\11\5\1\274\3\5\6\0\2\5\6\0\2\5\1\0"+
    "\3\5\12\0\1\52\1\53\1\5\2\0\1\5\1\275"+
    "\13\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\11\5\1\276\3\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\11\0\25\166\1\214"+
    "\1\277\31\166\1\0\1\52\1\53\1\5\2\0\1\300"+
    "\14\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\15\5\6\0\2\5\6\0"+
    "\1\301\1\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\11\5\1\302\3\5\6\0\2\5\6\0\2\5"+
    "\1\0\3\5\12\0\1\52\1\53\1\5\2\0\2\5"+
    "\1\303\12\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\4\5\1\304\10\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\4\5\1\305\10\5\6\0\2\5"+
    "\6\0\2\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\4\5\1\306\10\5\6\0\2\5\6\0\2\5"+
    "\1\0\3\5\12\0\1\52\1\53\1\5\2\0\4\5"+
    "\1\307\10\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\10\5\1\310\4\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\4\5\1\311\10\5\6\0\2\5"+
    "\6\0\2\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\6\5\1\312\6\5\6\0\2\5\6\0\2\5"+
    "\1\0\3\5\12\0\1\52\1\53\1\5\2\0\6\5"+
    "\1\313\6\5\6\0\2\5\6\0\2\5\1\0\3\5"+
    "\12\0\1\52\1\53\1\5\2\0\11\5\1\314\3\5"+
    "\6\0\2\5\6\0\2\5\1\0\3\5\12\0\1\52"+
    "\1\53\1\5\2\0\4\5\1\315\10\5\6\0\2\5"+
    "\6\0\2\5\1\0\3\5\12\0\1\52\1\53\1\5"+
    "\2\0\1\5\1\316\13\5\6\0\2\5\6\0\2\5"+
    "\1\0\3\5\12\0\1\52\1\53\1\5\2\0\1\317"+
    "\14\5\6\0\2\5\6\0\2\5\1\0\3\5\12\0"+
    "\1\52\1\53\1\5\2\0\4\5\1\320\10\5\6\0"+
    "\2\5\6\0\2\5\1\0\3\5\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7632];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\1\11\11\1\1\11"+
    "\6\1\6\11\2\1\1\11\1\1\3\11\4\1\1\0"+
    "\1\1\2\0\1\11\14\1\1\0\3\11\11\1\5\11"+
    "\1\1\2\0\16\1\1\0\11\1\1\0\16\1\1\0"+
    "\11\1\1\0\13\1\1\0\10\1\1\0\12\1\1\0"+
    "\7\1\1\0\10\1\1\0\7\1\1\11\5\1\1\11"+
    "\21\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public static String cadena;

/* ------------------------==: METODO DE ERROR LEXICO :==---------------------*/
    private void ErrorScan(int linea, int columna, String valor) {
        System.out.println("Error Lexico Iden: " + valor + ", " + linea + ", " + columna);
        cadena += "<tr>"
                + "<td><center><b>" + valor + "</b></center></td>"
                + "<td><center><b>" + linea + "</b></center></td>"
                + "<td><center><b>" + columna + "</b></center></td>"
                + "</tr>";
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scannerCJS(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public scannerCJS(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 58: 
          { System.out.println("setElemento");   return new Symbol (simbolosCJS.setelemento, yyline+1,yychar+1, new String (yytext()));
          }
        case 59: break;
        case 26: 
          { System.out.println("mayorIgual");   return new Symbol (simbolosCJS.mayorIgual, yyline+1,yychar+1, new String (yytext()));
          }
        case 60: break;
        case 16: 
          { System.out.println("puntoComa");   return new Symbol (simbolosCJS.puntoComa, yyline+1,yychar+1, new String (yytext()));
          }
        case 61: break;
        case 17: 
          { System.out.println("coma");   return new Symbol (simbolosCJS.coma, yyline+1,yychar+1, new String (yytext()));
          }
        case 62: break;
        case 43: 
          { System.out.println("detener");   return new Symbol (simbolosCJS.detener, yyline+1,yychar+1, new String (yytext()));
          }
        case 63: break;
        case 23: 
          { System.out.println("cadeba");                return new Symbol (simbolosCJS.cadena, yyline+1,yychar+1, new String (yytext()));
          }
        case 64: break;
        case 35: 
          { System.out.println("dimv");   return new Symbol (simbolosCJS.dimv, yyline+1,yychar+1, new String (yytext()));
          }
        case 65: break;
        case 55: 
          { System.out.println("observador");   return new Symbol (simbolosCJS.observador, yyline+1,yychar+1, new String (yytext()));
          }
        case 66: break;
        case 14: 
          { System.out.println("cierraPar");   return new Symbol (simbolosCJS.cierraPar, yyline+1,yychar+1, new String (yytext()));
          }
        case 67: break;
        case 15: 
          { System.out.println("dosPuntos");   return new Symbol (simbolosCJS.dosPuntos, yyline+1,yychar+1, new String (yytext()));
          }
        case 68: break;
        case 56: 
          { System.out.println("modificado");   return new Symbol (simbolosCJS.modificado, yyline+1,yychar+1, new String (yytext()));
          }
        case 69: break;
        case 13: 
          { System.out.println("abrePar");   return new Symbol (simbolosCJS.abrePar, yyline+1,yychar+1, new String (yytext()));
          }
        case 70: break;
        case 27: 
          { System.out.println("Coment simple");   /* se ignora*/
          }
        case 71: break;
        case 4: 
          { System.out.println("id");                return new Symbol (simbolosCJS.id, yyline+1,yychar+1, new String (yytext()));
          }
        case 72: break;
        case 22: 
          { System.out.println("not");  return new Symbol (simbolosCJS.not, yyline+1,yychar+1, new String (yytext()));
          }
        case 73: break;
        case 50: 
          { System.out.println("Coment Multi");   /* se ignora*/
          }
        case 74: break;
        case 12: 
          { System.out.println("cierraLlave");   return new Symbol (simbolosCJS.cierraLlave, yyline+1,yychar+1, new String (yytext()));
          }
        case 75: break;
        case 38: 
          { System.out.println("listo");   return new Symbol (simbolosCJS.listo, yyline+1,yychar+1, new String (yytext()));
          }
        case 76: break;
        case 1: 
          { ErrorScan(yyline,yychar,yytext());
          }
        case 77: break;
        case 11: 
          { System.out.println("abreLlave");   return new Symbol (simbolosCJS.abreLlave, yyline+1,yychar+1, new String (yytext()));
          }
        case 78: break;
        case 7: 
          { System.out.println("division");   return new Symbol (simbolosCJS.division, yyline+1,yychar+1, new String (yytext()));
          }
        case 79: break;
        case 6: 
          { System.out.println("menor");  return new Symbol (simbolosCJS.menor, yyline+1,yychar+1, new String (yytext()));
          }
        case 80: break;
        case 8: 
          { System.out.println("menos");   return new Symbol (simbolosCJS.menos, yyline+1,yychar+1, new String (yytext()));
          }
        case 81: break;
        case 47: 
          { System.out.println("cadebaVEctor");                return new Symbol (simbolosCJS.cadenaVector, yyline+1,yychar+1, new String (yytext()));
          }
        case 82: break;
        case 46: 
          { System.out.println("funcion");   return new Symbol (simbolosCJS.funcion, yyline+1,yychar+1, new String (yytext()));
          }
        case 83: break;
        case 57: 
          { System.out.println("selecciona");   return new Symbol (simbolosCJS.selecciona, yyline+1,yychar+1, new String (yytext()));
          }
        case 84: break;
        case 9: 
          { System.out.println("mayor");  return new Symbol (simbolosCJS.mayor, yyline+1,yychar+1, new String (yytext()));
          }
        case 85: break;
        case 30: 
          { System.out.println("igualIgual");   return new Symbol (simbolosCJS.igualIgual, yyline+1,yychar+1, new String (yytext()));
          }
        case 86: break;
        case 20: 
          { System.out.println("potencia");   return new Symbol (simbolosCJS.potencia, yyline+1,yychar+1, new String (yytext()));
          }
        case 87: break;
        case 21: 
          { System.out.println("residuo");   return new Symbol (simbolosCJS.residuo, yyline+1,yychar+1, new String (yytext()));
          }
        case 88: break;
        case 36: 
          { System.out.println("para");   return new Symbol (simbolosCJS.para, yyline+1,yychar+1, new String (yytext()));
          }
        case 89: break;
        case 31: 
          { System.out.println("disitnoA");   return new Symbol (simbolosCJS.distintoA, yyline+1,yychar+1, new String (yytext()));
          }
        case 90: break;
        case 52: 
          { System.out.println("cliqueado");  return new Symbol (simbolosCJS.cliqueado, yyline+1,yychar+1, new String (yytext()));
          }
        case 91: break;
        case 40: 
          { System.out.println("atexto");  return new Symbol (simbolosCJS.atexto, yyline+1,yychar+1, new String (yytext()));
          }
        case 92: break;
        case 45: 
          { System.out.println("mensaje");   return new Symbol (simbolosCJS.mensaje, yyline+1,yychar+1, new String (yytext()));
          }
        case 93: break;
        case 2: 
          { System.out.println("nu mero");                return new Symbol (simbolosCJS.numero, yyline+1,yychar+1, new String (yytext()));
          }
        case 94: break;
        case 37: 
          { System.out.println("sino");   return new Symbol (simbolosCJS.sino, yyline+1,yychar+1, new String (yytext()));
          }
        case 95: break;
        case 25: 
          { System.out.println("menosMenos");   return new Symbol (simbolosCJS.menosMenos, yyline+1,yychar+1, new String (yytext()));
          }
        case 96: break;
        case 39: 
          { System.out.println("falso");               return new Symbol (simbolosCJS.falso, yyline+1,yychar+1, new String (yytext()));
          }
        case 97: break;
        case 42: 
          { System.out.println("obtener");   return new Symbol (simbolosCJS.obtener, yyline+1,yychar+1, new String (yytext()));
          }
        case 98: break;
        case 33: 
          { System.out.println("or");   return new Symbol (simbolosCJS.or, yyline+1,yychar+1, new String (yytext()));
          }
        case 99: break;
        case 32: 
          { System.out.println("and");   return new Symbol (simbolosCJS.and, yyline+1,yychar+1, new String (yytext()));
          }
        case 100: break;
        case 3: 
          { System.out.println("punto");   return new Symbol (simbolosCJS.punto, yyline+1,yychar+1, new String (yytext()));
          }
        case 101: break;
        case 53: 
          { System.out.println("documento");   return new Symbol (simbolosCJS.documento, yyline+1,yychar+1, new String (yytext()));
          }
        case 102: break;
        case 29: 
          { System.out.println("masMas");   return new Symbol (simbolosCJS.masMas, yyline+1,yychar+1, new String (yytext()));
          }
        case 103: break;
        case 18: 
          { System.out.println("mas");   return new Symbol (simbolosCJS.mas, yyline+1,yychar+1, new String (yytext()));
          }
        case 104: break;
        case 54: 
          { System.out.println("verdadero");               return new Symbol (simbolosCJS.verdadero, yyline+1,yychar+1, new String (yytext()));
          }
        case 105: break;
        case 41: 
          { System.out.println("conteo");   return new Symbol (simbolosCJS.conteo, yyline+1,yychar+1, new String (yytext()));
          }
        case 106: break;
        case 5: 
          { System.out.println("comillaSimple");   return new Symbol (simbolosCJS.comillaSimple, yyline+1,yychar+1, new String (yytext()));
          }
        case 107: break;
        case 51: 
          { System.out.println("mientras");  return new Symbol (simbolosCJS.mientras, yyline+1,yychar+1, new String (yytext()));
          }
        case 108: break;
        case 44: 
          { System.out.println("defecto");   return new Symbol (simbolosCJS.defecto, yyline+1,yychar+1, new String (yytext()));
          }
        case 109: break;
        case 28: 
          { System.out.println("si");   return new Symbol (simbolosCJS.si, yyline+1,yychar+1, new String (yytext()));
          }
        case 110: break;
        case 49: 
          { System.out.println("retornar");   return new Symbol (simbolosCJS.retornar, yyline+1,yychar+1, new String (yytext()));
          }
        case 111: break;
        case 19: 
          { System.out.println("multiplicacion");   return new Symbol (simbolosCJS.multiplicacion, yyline+1,yychar+1, new String (yytext()));
          }
        case 112: break;
        case 24: 
          { System.out.println("menorIgual");   return new Symbol (simbolosCJS.menorIgual, yyline+1,yychar+1, new String (yytext()));
          }
        case 113: break;
        case 10: 
          { /* Se ignoran */
          }
        case 114: break;
        case 34: 
          { System.out.println("caso");   return new Symbol (simbolosCJS.caso, yyline+1,yychar+1, new String (yytext()));
          }
        case 115: break;
        case 48: 
          { System.out.println("imprimir");   return new Symbol (simbolosCJS.imprimir, yyline+1,yychar+1, new String (yytext()));
          }
        case 116: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(simbolosCJS.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
