
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 13 13:43:26 CST 2018
//----------------------------------------------------

package proyecto1_201122872.AnalizadorCHTML;

import proyecto1_201122872.AnalizadorCHTML.simbolosCHTML;
import java_cup.runtime.*;
import java.io.*;
import java.lang.*;
import java.util.*;
import java.util.ArrayList;

/** CUP v0.10k generated parser.
  * @version Tue Feb 13 13:43:26 CST 2018
  */
public class Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\224\000\002\002\004\000\002\003\003\000\002\020" +
    "\006\000\002\021\006\000\002\022\006\000\002\023\006" +
    "\000\002\012\006\000\002\013\006\000\002\014\006\000" +
    "\002\015\006\000\002\016\006\000\002\024\003\000\002" +
    "\024\003\000\002\024\003\000\002\024\003\000\002\024" +
    "\003\000\002\025\004\000\002\025\003\000\002\106\003" +
    "\000\002\106\003\000\002\107\004\000\002\107\003\000" +
    "\002\105\003\000\002\105\003\000\002\102\004\000\002" +
    "\102\003\000\002\110\003\000\002\110\003\000\002\103" +
    "\004\000\002\103\003\000\002\104\003\000\002\104\003" +
    "\000\002\104\003\000\002\077\004\000\002\077\003\000" +
    "\002\100\003\000\002\100\003\000\002\101\003\000\002" +
    "\101\004\000\002\052\005\000\002\052\006\000\002\053" +
    "\005\000\002\054\005\000\002\054\006\000\002\055\005" +
    "\000\002\056\005\000\002\056\006\000\002\057\005\000" +
    "\002\060\006\000\002\060\005\000\002\032\005\000\002" +
    "\032\006\000\002\033\005\000\002\034\005\000\002\034" +
    "\006\000\002\035\005\000\002\040\005\000\002\040\006" +
    "\000\002\041\005\000\002\036\005\000\002\036\006\000" +
    "\002\036\005\000\002\042\005\000\002\042\006\000\002" +
    "\043\005\000\002\074\005\000\002\074\006\000\002\075" +
    "\005\000\002\044\005\000\002\044\006\000\002\045\005" +
    "\000\002\046\006\000\002\046\005\000\002\047\005\000" +
    "\002\050\005\000\002\050\005\000\002\051\005\000\002" +
    "\062\006\000\002\062\005\000\002\063\005\000\002\064" +
    "\005\000\002\064\006\000\002\065\005\000\002\070\006" +
    "\000\002\070\005\000\002\071\005\000\002\066\005\000" +
    "\002\066\006\000\002\067\005\000\002\076\005\000\002" +
    "\072\006\000\002\072\005\000\002\073\005\000\002\026" +
    "\005\000\002\026\006\000\002\027\005\000\002\030\005" +
    "\000\002\030\006\000\002\031\005\000\002\111\005\000" +
    "\002\135\004\000\002\011\003\000\002\011\003\000\002" +
    "\011\003\000\002\010\004\000\002\010\003\000\002\112" +
    "\005\000\002\112\004\000\002\113\004\000\002\114\004" +
    "\000\002\115\005\000\002\116\004\000\002\116\005\000" +
    "\002\117\005\000\002\117\004\000\002\120\005\000\002" +
    "\120\004\000\002\121\005\000\002\121\004\000\002\122" +
    "\005\000\002\122\004\000\002\123\005\000\002\123\004" +
    "\000\002\124\005\000\002\124\004\000\002\130\005\000" +
    "\002\130\004\000\002\131\004\000\002\131\003\000\002" +
    "\125\005\000\002\125\004\000\002\126\005\000\002\126" +
    "\004\000\002\127\003\000\002\134\005\000\002\134\004" +
    "\000\002\132\003\000\002\132\003\000\002\132\003\000" +
    "\002\132\003\000\002\132\003\000\002\132\003\000\002" +
    "\132\003\000\002\132\003\000\002\132\003\000\002\132" +
    "\003\000\002\133\004\000\002\133\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u0106\000\004\004\006\001\002\000\004\002\000\001" +
    "\002\000\004\004\053\001\002\000\004\007\011\001\002" +
    "\000\004\002\010\001\002\000\004\002\001\001\002\000" +
    "\016\005\025\060\012\061\024\062\026\063\013\064\022" +
    "\001\002\000\004\074\045\001\002\000\004\074\042\001" +
    "\002\000\026\005\ufff5\060\ufff5\061\ufff5\062\ufff5\063\ufff5" +
    "\064\ufff5\065\ufff5\066\ufff5\067\ufff5\070\ufff5\001\002\000" +
    "\016\005\ufff0\060\ufff0\061\ufff0\062\ufff0\063\ufff0\064\ufff0" +
    "\001\002\000\026\005\ufff6\060\ufff6\061\ufff6\062\ufff6\063" +
    "\ufff6\064\ufff6\065\ufff6\066\ufff6\067\ufff6\070\ufff6\001\002" +
    "\000\026\005\ufff3\060\ufff3\061\ufff3\062\ufff3\063\ufff3\064" +
    "\ufff3\065\ufff3\066\ufff3\067\ufff3\070\ufff3\001\002\000\026" +
    "\005\ufff4\060\ufff4\061\ufff4\062\ufff4\063\ufff4\064\ufff4\065" +
    "\ufff4\066\ufff4\067\ufff4\070\ufff4\001\002\000\016\005\041" +
    "\060\012\061\024\062\026\063\013\064\022\001\002\000" +
    "\004\074\035\001\002\000\026\005\ufff2\060\ufff2\061\ufff2" +
    "\062\ufff2\063\ufff2\064\ufff2\065\ufff2\066\ufff2\067\ufff2\070" +
    "\ufff2\001\002\000\004\074\032\001\002\000\004\004\uffa1" +
    "\001\002\000\004\074\027\001\002\000\004\077\030\001" +
    "\002\000\004\075\031\001\002\000\026\005\ufff9\060\ufff9" +
    "\061\ufff9\062\ufff9\063\ufff9\064\ufff9\065\ufff9\066\ufff9\067" +
    "\ufff9\070\ufff9\001\002\000\004\077\033\001\002\000\004" +
    "\075\034\001\002\000\026\005\ufffa\060\ufffa\061\ufffa\062" +
    "\ufffa\063\ufffa\064\ufffa\065\ufffa\066\ufffa\067\ufffa\070\ufffa" +
    "\001\002\000\004\077\036\001\002\000\004\075\037\001" +
    "\002\000\026\005\ufff7\060\ufff7\061\ufff7\062\ufff7\063\ufff7" +
    "\064\ufff7\065\ufff7\066\ufff7\067\ufff7\070\ufff7\001\002\000" +
    "\016\005\ufff1\060\ufff1\061\ufff1\062\ufff1\063\ufff1\064\ufff1" +
    "\001\002\000\004\004\uffa0\001\002\000\004\077\043\001" +
    "\002\000\004\075\044\001\002\000\026\005\ufff8\060\ufff8" +
    "\061\ufff8\062\ufff8\063\ufff8\064\ufff8\065\ufff8\066\ufff8\067" +
    "\ufff8\070\ufff8\001\002\000\004\077\046\001\002\000\004" +
    "\075\047\001\002\000\026\005\ufffb\060\ufffb\061\ufffb\062" +
    "\ufffb\063\ufffb\064\ufffb\065\ufffb\066\ufffb\067\ufffb\070\ufffb" +
    "\001\002\000\004\004\344\001\002\000\004\004\064\001" +
    "\002\000\004\004\061\001\002\000\004\011\054\001\002" +
    "\000\016\005\056\060\012\061\024\062\026\063\013\064" +
    "\022\001\002\000\016\005\057\060\012\061\024\062\026" +
    "\063\013\064\022\001\002\000\004\004\uffa4\001\002\000" +
    "\004\004\uffa3\001\002\000\004\002\uff9e\001\002\000\004" +
    "\010\062\001\002\000\004\005\063\001\002\000\004\002" +
    "\uff9f\001\002\000\004\017\327\001\002\000\004\004\uff9d" +
    "\001\002\000\004\004\103\001\002\000\004\004\322\001" +
    "\002\000\006\004\313\006\315\001\002\000\006\004\306" +
    "\006\307\001\002\000\004\004\uff78\001\002\000\004\004" +
    "\uff70\001\002\000\006\004\301\077\300\001\002\000\006" +
    "\004\272\006\273\001\002\000\004\004\uff77\001\002\000" +
    "\004\004\uff74\001\002\000\004\004\uff92\001\002\000\004" +
    "\004\uff75\001\002\000\006\004\263\006\265\001\002\000" +
    "\044\020\206\023\175\025\170\027\201\031\202\033\176" +
    "\045\205\047\200\051\174\055\173\057\203\060\012\061" +
    "\024\062\026\063\013\064\022\066\204\001\002\000\004" +
    "\004\uff76\001\002\000\004\004\137\001\002\000\004\004" +
    "\uff7c\001\002\000\004\004\uff6e\001\002\000\006\004\130" +
    "\006\131\001\002\000\004\004\uff79\001\002\000\004\004" +
    "\uff73\001\002\000\004\004\uff71\001\002\000\004\004\uff72" +
    "\001\002\000\006\004\122\077\121\001\002\000\004\004" +
    "\103\001\002\000\004\004\uff91\001\002\000\004\004\uff6f" +
    "\001\002\000\004\004\122\001\002\000\004\056\124\001" +
    "\002\000\004\004\uff7d\001\002\000\004\005\125\001\002" +
    "\000\004\004\uffa5\001\002\000\004\004\uff7e\001\002\000" +
    "\004\004\uff8f\001\002\000\004\026\133\001\002\000\004" +
    "\004\130\001\002\000\004\004\uff90\001\002\000\004\005" +
    "\134\001\002\000\004\004\uffc1\001\002\000\004\004\uff81" +
    "\001\002\000\004\004\uff7f\001\002\000\006\052\153\053" +
    "\152\001\002\000\004\004\137\001\002\000\006\004\142" +
    "\006\144\001\002\000\004\054\146\001\002\000\004\004" +
    "\uff83\001\002\000\004\004\142\001\002\000\004\004\uff84" +
    "\001\002\000\004\005\147\001\002\000\004\004\uffa9\001" +
    "\002\000\004\004\uff82\001\002\000\004\004\uff80\001\002" +
    "\000\020\005\162\060\012\061\024\062\026\063\013\064" +
    "\022\065\156\001\002\000\004\005\154\001\002\000\004" +
    "\004\uffac\001\002\000\020\005\uffee\060\uffee\061\uffee\062" +
    "\uffee\063\uffee\064\uffee\065\uffee\001\002\000\004\074\165" +
    "\001\002\000\020\005\uffef\060\uffef\061\uffef\062\uffef\063" +
    "\uffef\064\uffef\065\uffef\001\002\000\020\005\164\060\012" +
    "\061\024\062\026\063\013\064\022\065\156\001\002\000" +
    "\020\005\uffec\060\uffec\061\uffec\062\uffec\063\uffec\064\uffec" +
    "\065\uffec\001\002\000\006\004\uffab\006\uffab\001\002\000" +
    "\020\005\uffed\060\uffed\061\uffed\062\uffed\063\uffed\064\uffed" +
    "\065\uffed\001\002\000\006\004\uffaa\006\uffaa\001\002\000" +
    "\004\077\166\001\002\000\004\075\167\001\002\000\020" +
    "\005\ufffc\060\ufffc\061\ufffc\062\ufffc\063\ufffc\064\ufffc\065" +
    "\ufffc\001\002\000\016\005\261\060\012\061\024\062\026" +
    "\063\013\064\022\001\002\000\004\005\257\001\002\000" +
    "\004\005\uffe6\001\002\000\016\005\255\060\012\061\024" +
    "\062\026\063\013\064\022\001\002\000\020\005\252\060" +
    "\012\061\024\062\026\063\013\064\022\066\204\001\002" +
    "\000\016\005\247\060\012\061\024\062\026\063\013\064" +
    "\022\001\002\000\004\005\245\001\002\000\004\005\uffe7" +
    "\001\002\000\016\005\243\060\012\061\024\062\026\063" +
    "\013\064\022\001\002\000\020\005\237\060\012\061\024" +
    "\062\026\063\013\064\022\066\204\001\002\000\022\005" +
    "\225\060\012\061\024\062\026\063\013\064\022\066\204" +
    "\067\217\001\002\000\004\005\216\001\002\000\004\074" +
    "\213\001\002\000\016\005\211\060\012\061\024\062\026" +
    "\063\013\064\022\001\002\000\004\005\207\001\002\000" +
    "\004\004\uffc7\001\002\000\016\005\212\060\012\061\024" +
    "\062\026\063\013\064\022\001\002\000\006\004\uffb3\006" +
    "\uffb3\001\002\000\006\004\uffb4\006\uffb4\001\002\000\004" +
    "\077\214\001\002\000\004\075\215\001\002\000\022\005" +
    "\ufffe\060\ufffe\061\ufffe\062\ufffe\063\ufffe\064\ufffe\066\ufffe" +
    "\067\ufffe\001\002\000\004\004\uffa8\001\002\000\004\074" +
    "\230\001\002\000\022\005\uffe1\060\uffe1\061\uffe1\062\uffe1" +
    "\063\uffe1\064\uffe1\066\uffe1\067\uffe1\001\002\000\022\005" +
    "\uffdf\060\uffdf\061\uffdf\062\uffdf\063\uffdf\064\uffdf\066\uffdf" +
    "\067\uffdf\001\002\000\022\005\uffe2\060\uffe2\061\uffe2\062" +
    "\uffe2\063\uffe2\064\uffe2\066\uffe2\067\uffe2\001\002\000\022" +
    "\005\uffe3\060\uffe3\061\uffe3\062\uffe3\063\uffe3\064\uffe3\066" +
    "\uffe3\067\uffe3\001\002\000\022\005\227\060\012\061\024" +
    "\062\026\063\013\064\022\066\204\067\217\001\002\000" +
    "\006\004\uffb9\006\uffb9\001\002\000\022\005\uffe0\060\uffe0" +
    "\061\uffe0\062\uffe0\063\uffe0\064\uffe0\066\uffe0\067\uffe0\001" +
    "\002\000\006\004\uffba\006\uffba\001\002\000\004\077\231" +
    "\001\002\000\004\075\232\001\002\000\022\005\uffff\060" +
    "\uffff\061\uffff\062\uffff\063\uffff\064\uffff\066\uffff\067\uffff" +
    "\001\002\000\020\005\uffe8\060\uffe8\061\uffe8\062\uffe8\063" +
    "\uffe8\064\uffe8\066\uffe8\001\002\000\020\005\241\060\012" +
    "\061\024\062\026\063\013\064\022\066\204\001\002\000" +
    "\020\005\uffea\060\uffea\061\uffea\062\uffea\063\uffea\064\uffea" +
    "\066\uffea\001\002\000\020\005\uffeb\060\uffeb\061\uffeb\062" +
    "\uffeb\063\uffeb\064\uffeb\066\uffeb\001\002\000\006\004\uffbd" +
    "\077\uffbd\001\002\000\020\005\uffe9\060\uffe9\061\uffe9\062" +
    "\uffe9\063\uffe9\064\uffe9\066\uffe9\001\002\000\006\004\uffbc" +
    "\077\uffbc\001\002\000\016\005\244\060\012\061\024\062" +
    "\026\063\013\064\022\001\002\000\006\004\uffb1\006\uffb1" +
    "\001\002\000\006\004\uffb0\006\uffb0\001\002\000\006\004" +
    "\uffb7\006\uffb7\001\002\000\016\005\250\060\012\061\024" +
    "\062\026\063\013\064\022\001\002\000\004\004\uffc0\001" +
    "\002\000\004\004\uffbf\001\002\000\020\005\253\060\012" +
    "\061\024\062\026\063\013\064\022\066\204\001\002\000" +
    "\004\004\uffad\001\002\000\004\004\uffae\001\002\000\016" +
    "\005\256\060\012\061\024\062\026\063\013\064\022\001" +
    "\002\000\006\004\uffa6\077\uffa6\001\002\000\006\004\uffa7" +
    "\077\uffa7\001\002\000\006\004\uffb6\006\uffb6\001\002\000" +
    "\016\005\262\060\012\061\024\062\026\063\013\064\022" +
    "\001\002\000\006\004\uffc3\006\uffc3\001\002\000\006\004" +
    "\uffc2\006\uffc2\001\002\000\004\046\267\001\002\000\004" +
    "\004\uff87\001\002\000\004\004\263\001\002\000\004\004" +
    "\uff88\001\002\000\004\005\270\001\002\000\004\004\uffb2" +
    "\001\002\000\004\004\uff8b\001\002\000\004\032\275\001" +
    "\002\000\004\004\272\001\002\000\004\004\uff8c\001\002" +
    "\000\004\005\276\001\002\000\004\004\uffb8\001\002\000" +
    "\004\004\uff8d\001\002\000\004\004\301\001\002\000\004" +
    "\030\302\001\002\000\004\005\303\001\002\000\004\004" +
    "\uffbb\001\002\000\004\004\uff8e\001\002\000\004\004\uff85" +
    "\001\002\000\004\050\311\001\002\000\004\004\306\001" +
    "\002\000\004\004\uff86\001\002\000\004\005\312\001\002" +
    "\000\004\004\uffaf\001\002\000\004\034\317\001\002\000" +
    "\004\004\uff89\001\002\000\004\004\313\001\002\000\004" +
    "\004\uff8a\001\002\000\004\005\320\001\002\000\004\004" +
    "\uffb5\001\002\000\004\004\uff7a\001\002\000\044\023\175" +
    "\024\325\025\170\027\201\031\202\033\176\045\205\047" +
    "\200\051\174\055\173\057\203\060\012\061\024\062\026" +
    "\063\013\064\022\066\204\001\002\000\004\004\322\001" +
    "\002\000\004\004\uff7b\001\002\000\004\005\326\001\002" +
    "\000\004\004\uffbe\001\002\000\020\005\335\060\012\061" +
    "\024\062\026\063\013\064\022\070\331\001\002\000\020" +
    "\005\uffde\060\uffde\061\uffde\062\uffde\063\uffde\064\uffde\070" +
    "\uffde\001\002\000\004\074\340\001\002\000\020\005\uffdd" +
    "\060\uffdd\061\uffdd\062\uffdd\063\uffdd\064\uffdd\070\uffdd\001" +
    "\002\000\020\005\337\060\012\061\024\062\026\063\013" +
    "\064\022\070\331\001\002\000\020\005\uffdc\060\uffdc\061" +
    "\uffdc\062\uffdc\063\uffdc\064\uffdc\070\uffdc\001\002\000\004" +
    "\004\uffc9\001\002\000\020\005\uffdb\060\uffdb\061\uffdb\062" +
    "\uffdb\063\uffdb\064\uffdb\070\uffdb\001\002\000\004\004\uffc8" +
    "\001\002\000\004\077\341\001\002\000\004\075\342\001" +
    "\002\000\020\005\ufffd\060\ufffd\061\ufffd\062\ufffd\063\ufffd" +
    "\064\ufffd\070\ufffd\001\002\000\004\004\uff9a\001\002\000" +
    "\014\012\374\013\375\015\373\021\371\022\372\001\002" +
    "\000\004\004\344\001\002\000\004\004\uff9b\001\002\000" +
    "\004\004\uff98\001\002\000\004\004\uff96\001\002\000\004" +
    "\004\uff9c\001\002\000\004\004\363\001\002\000\004\004" +
    "\360\001\002\000\004\006\355\001\002\000\002\001\002" +
    "\000\004\004\uff93\001\002\000\004\004\uff95\001\002\000" +
    "\004\014\361\001\002\000\004\005\362\001\002\000\004" +
    "\004\uffcd\001\002\000\004\016\365\001\002\000\004\004" +
    "\uff94\001\002\000\004\005\366\001\002\000\004\004\uffca" +
    "\001\002\000\004\004\uff99\001\002\000\004\004\uff97\001" +
    "\002\000\016\005\u0107\060\012\061\024\062\026\063\013" +
    "\064\022\001\002\000\004\005\u0105\001\002\000\006\005" +
    "\u0103\067\217\001\002\000\004\005\u0101\001\002\000\006" +
    "\005\377\067\217\001\002\000\004\005\u0100\001\002\000" +
    "\004\004\uffcf\001\002\000\004\004\uffce\001\002\000\004" +
    "\004\uffa2\001\002\000\004\005\u0104\001\002\000\004\004" +
    "\uffcc\001\002\000\004\004\uffcb\001\002\000\004\006\uffc4" +
    "\001\002\000\016\005\u0108\060\012\061\024\062\026\063" +
    "\013\064\022\001\002\000\004\006\uffc6\001\002\000\004" +
    "\006\uffc5\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u0106\000\010\003\006\030\004\111\003\001\001\000" +
    "\002\001\001\000\010\026\047\112\050\135\051\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\012\015\013\013\014\017\015\016\016\022\024\014" +
    "\025\020\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\012\015\013\013\014" +
    "\017\015\016\016\022\024\037\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\024\010\344\011\346\027" +
    "\347\032\352\034\351\036\353\113\350\114\345\115\342" +
    "\001\001\000\006\040\065\116\064\001\001\000\004\031" +
    "\057\001\001\000\002\001\001\000\020\012\015\013\013" +
    "\014\017\015\016\016\022\024\014\025\054\001\001\000" +
    "\016\012\015\013\013\014\017\015\016\016\022\024\037" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\060\041\077\042" +
    "\107\044\073\046\074\050\067\062\101\064\070\070\104" +
    "\072\114\074\066\076\105\117\110\120\071\121\075\122" +
    "\103\123\100\124\076\125\111\126\113\127\112\132\106" +
    "\133\115\134\072\001\001\000\060\042\107\044\073\046" +
    "\074\050\067\062\101\064\070\070\104\072\114\074\066" +
    "\075\320\076\105\117\110\120\071\121\075\122\103\123" +
    "\100\124\076\125\111\126\113\127\112\132\106\133\322" +
    "\134\072\001\001\000\004\051\313\001\001\000\004\065" +
    "\304\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\045\276\001\001\000\004\047\270\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\063\263\001\001\000\022\012\015\013\013\014" +
    "\017\015\016\016\022\021\171\024\176\110\170\001\001" +
    "\000\002\001\001\000\012\066\140\071\135\130\134\131" +
    "\137\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\043\126\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\073\122\001\001" +
    "\000\056\041\116\042\107\044\073\046\074\050\067\062" +
    "\101\064\070\070\104\072\114\074\066\076\105\117\110" +
    "\120\071\121\075\122\103\123\100\124\076\125\111\126" +
    "\113\127\112\132\117\134\072\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\073\125\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\043\131\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\066\140\071\150\130\147\001\001" +
    "\000\004\067\142\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\067\144\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\024\012\015\013\013\014\017\015\016\016\022" +
    "\023\154\024\156\106\160\107\157\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\012\015\013\013\014\017\015" +
    "\016\016\022\023\154\024\156\106\162\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\012\015\013\013\014\017\015\016\016\022\024" +
    "\014\025\257\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\012\015\013\013\014\017\015\016\016\022\024" +
    "\014\025\253\001\001\000\024\012\015\013\013\014\017" +
    "\015\016\016\022\021\234\024\235\102\250\105\232\001" +
    "\001\000\020\012\015\013\013\014\017\015\016\016\022" +
    "\024\014\025\245\001\001\000\002\001\001\000\002\001" +
    "\001\000\020\012\015\013\013\014\017\015\016\016\022" +
    "\024\014\025\241\001\001\000\024\012\015\013\013\014" +
    "\017\015\016\016\022\021\234\024\235\102\233\105\232" +
    "\001\001\000\026\012\015\013\013\014\017\015\016\016" +
    "\022\020\217\021\221\024\222\077\223\104\220\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\012\015\013" +
    "\013\014\017\015\016\016\022\024\014\025\207\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\012\015\013" +
    "\013\014\017\015\016\016\022\024\037\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\012\015\013\013\014\017\015\016" +
    "\016\022\020\217\021\221\024\222\104\225\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\012\015\013\013\014\017\015\016\016\022" +
    "\021\234\024\235\105\237\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\012\015\013\013\014\017\015\016\016" +
    "\022\024\037\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\012\015\013\013\014\017\015" +
    "\016\016\022\024\037\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\012\015\013\013\014\017\015\016\016" +
    "\022\021\234\024\235\105\237\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\012\015\013\013\014\017\015" +
    "\016\016\022\024\037\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\012\015\013\013\014" +
    "\017\015\016\016\022\024\037\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\063\265\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\047\273\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\045\303\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\065\307\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\051\315\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\012\015\013" +
    "\013\014\017\015\016\016\022\021\171\024\176\110\170" +
    "\001\001\000\056\042\107\044\073\046\074\050\067\062" +
    "\101\064\070\070\104\072\114\074\066\075\323\076\105" +
    "\117\110\120\071\121\075\122\103\123\100\124\076\125" +
    "\111\126\113\127\112\132\117\134\072\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\024\012" +
    "\015\013\013\014\017\015\016\016\022\022\331\024\327" +
    "\100\333\101\332\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\012\015\013\013\014\017" +
    "\015\016\016\022\022\331\024\327\100\335\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\022\011\366" +
    "\027\367\032\352\034\351\036\353\113\350\114\345\115" +
    "\342\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\035\363\001\001\000" +
    "\004\033\356\001\001\000\002\001\001\000\004\037\355" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\012\015\013\013" +
    "\014\017\015\016\016\022\024\014\025\u0105\001\001\000" +
    "\002\001\001\000\004\020\u0101\001\001\000\002\001\001" +
    "\000\004\020\375\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\012\015\013\013\014\017\015\016\016\022\024\037" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



 /* -------------------------==: DECLARAR EL ARBOL :==--------------------------*/
    //public Nodo Gramaticas;     
    public static String cadena;

/* -------------------------==: ERROR SINTACTICO :==--------------------------*/
public void syntax_error(Symbol s){
    System.out.println("Error Sintactico -> lexema: " +s.value+" Linea: " +s.right+ " Columna: "+s.left);
    cadena += "<tr>"
                + "<td><center><b>" + s.value + "</b></center></td>"
                + "<td><center><b>" + s.right + "</b></center></td>"
                + "<td><center><b>" + s.left+ "</b></center></td>"
                + "</tr>";
}

/* ------------------==: ERROR SINTACTICO NO RECUPERABLE :==------------------*/
public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
    System.out.println("Error Sintactico No Recuperable-> Lexema: " +s.value+" Linea: "+s.right+ " Columna: "+s.left);
     cadena += "<tr>"
                + "<td><center><b>" + s.value + "</b></center></td>"
                + "<td><center><b>" + s.right + "</b></center></td>"
                + "<td><center><b>" + s.left+ "</b></center></td>"
                + "</tr>";
}


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Parser$actions {


//Operaciones_Listas operaciones = new Operaciones_Listas();


  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 147: // cuerpoCuerpo ::= sentenciaCuerpo 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(89/*cuerpoCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 146: // cuerpoCuerpo ::= cuerpoCuerpo sentenciaCuerpo 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(89/*cuerpoCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 145: // sentenciaCuerpo ::= PANEL 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(88/*sentenciaCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 144: // sentenciaCuerpo ::= SALTO 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(88/*sentenciaCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 143: // sentenciaCuerpo ::= SPINNER 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(88/*sentenciaCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 142: // sentenciaCuerpo ::= CAJA 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(88/*sentenciaCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 141: // sentenciaCuerpo ::= CAJA_TEXTO 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(88/*sentenciaCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 140: // sentenciaCuerpo ::= TEXTO_A 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(88/*sentenciaCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 139: // sentenciaCuerpo ::= ENLACE 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(88/*sentenciaCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 138: // sentenciaCuerpo ::= BOTON 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(88/*sentenciaCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 137: // sentenciaCuerpo ::= IMAGEN 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(88/*sentenciaCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 136: // sentenciaCuerpo ::= TEXTO 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(88/*sentenciaCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 135: // PANEL ::= tagPanel tagFinPanel 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(90/*PANEL*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 134: // PANEL ::= tagPanel cuerpoCuerpo tagFinPanel 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(90/*PANEL*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 133: // SALTO ::= tagSaltoFin 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(85/*SALTO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 132: // SPINNER ::= tagSpinner tagFinSpinner 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(84/*SPINNER*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 131: // SPINNER ::= tagSpinner cadena tagFinSpinner 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(84/*SPINNER*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 130: // CAJA ::= tagCaja tagFinCaja 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(83/*CAJA*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 129: // CAJA ::= tagCaja listaOpciones tagFinCaja 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(83/*CAJA*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 128: // listaOpciones ::= OPCION 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(87/*listaOpciones*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 127: // listaOpciones ::= listaOpciones OPCION 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(87/*listaOpciones*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 126: // OPCION ::= tagOpcion tagFinOpcion 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(86/*OPCION*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 125: // OPCION ::= tagOpcion cadena2 tagFinOpcion 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(86/*OPCION*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 124: // CAJA_TEXTO ::= tagCaja_texto tagFinCaja_texto 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(82/*CAJA_TEXTO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 123: // CAJA_TEXTO ::= tagCaja_texto cadena2 tagFinCaja_texto 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(82/*CAJA_TEXTO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 122: // TEXTO_A ::= tagTexto_a tagFinTexto_a 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(81/*TEXTO_A*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 121: // TEXTO_A ::= tagTexto_a cadena2 tagFinTexto_a 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(81/*TEXTO_A*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 120: // ENLACE ::= tagEnlace tagFinEnlace 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(80/*ENLACE*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 119: // ENLACE ::= tagEnlace cadena2 tagFinEnlace 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(80/*ENLACE*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 118: // BOTON ::= tagBoton tagFinBoton 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(79/*BOTON*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 117: // BOTON ::= tagBoton cadena2 tagFinBoton 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(79/*BOTON*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 116: // IMAGEN ::= tagImagen tagFinImagen 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(78/*IMAGEN*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 115: // IMAGEN ::= tagImagen cadena tagFinImagen 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(78/*IMAGEN*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 114: // TEXTO ::= tagTexto tagFinTexto 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(77/*TEXTO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 113: // TEXTO ::= tagTexto cadena2 tagFinTexto 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(77/*TEXTO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 112: // CUERPO ::= tagCuerpo cuerpoCuerpo tagFinCuerpo 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(76/*CUERPO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 111: // CUERPO ::= tagCuerpo tagFinCuerpo 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(76/*CUERPO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 110: // TITULO ::= tagTitulo cadena2 tagFinTitulo 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(75/*TITULO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 109: // CCSS ::= tagCcss tagFinCcss 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(74/*CCSS*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 108: // CCJS ::= tagCjs tagFinCjs 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(73/*CCJS*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 107: // ENCABEZADO ::= tagEncabezado tagFinEncabezado 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(72/*ENCABEZADO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 106: // ENCABEZADO ::= tagEncabezado cuerpoHeader tagFinEncabezado 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(72/*ENCABEZADO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 105: // cuerpoHeader ::= elementoHeader 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(6/*cuerpoHeader*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // cuerpoHeader ::= cuerpoHeader elementoHeader 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(6/*cuerpoHeader*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // elementoHeader ::= TITULO 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(7/*elementoHeader*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // elementoHeader ::= CCSS 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(7/*elementoHeader*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // elementoHeader ::= CCJS 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(7/*elementoHeader*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // cuerpoCHTML ::= ENCABEZADO CUERPO 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(91/*cuerpoCHTML*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // CHTML ::= tagChtml cuerpoCHTML tagFinChtml 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(71/*CHTML*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // tagFinChtml ::= menor finChtml mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(23/*tagFinChtml*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // tagChtml ::= menor chtml listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(22/*tagChtml*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // tagChtml ::= menor chtml mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(22/*tagChtml*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // tagFinEncabezado ::= menor finEncabezado mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(21/*tagFinEncabezado*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // tagEncabezado ::= menor encabezado listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(20/*tagEncabezado*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // tagEncabezado ::= menor encabezado mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(20/*tagEncabezado*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // tagFinSpinner ::= menor finSpinner mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(57/*tagFinSpinner*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // tagSpinner ::= menor spinner mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(56/*tagSpinner*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // tagSpinner ::= menor spinner listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(56/*tagSpinner*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // tagSaltoFin ::= menor saltoFin mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(60/*tagSaltoFin*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // tagFinOpcion ::= menor finOpcion mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(53/*tagFinOpcion*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // tagOpcion ::= menor opcion listaPropiedadesOpcion mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(52/*tagOpcion*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // tagOpcion ::= menor opcion mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(52/*tagOpcion*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // tagFinCaja ::= menor finCaja mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(55/*tagFinCaja*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // tagCaja ::= menor caja mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(54/*tagCaja*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // tagCaja ::= menor caja listaPropiedadeesCajaOpciones mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(54/*tagCaja*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // tagFinCaja_texto ::= menor finCaja_texto mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(51/*tagFinCaja_texto*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // tagCaja_texto ::= menor caja_texto listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(50/*tagCaja_texto*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // tagCaja_texto ::= menor caja_texto mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(50/*tagCaja_texto*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // tagFinTexto_a ::= menor finTexto_a mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(49/*tagFinTexto_a*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // tagTexto_a ::= menor texto_a mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(48/*tagTexto_a*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // tagTexto_a ::= menor texto_a listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(48/*tagTexto_a*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // tagFinEnlace ::= menor finEnlace mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(39/*tagFinEnlace*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // tagEnlace ::= menor propiedadEnlace mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(38/*tagEnlace*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // tagEnlace ::= menor enlace mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(38/*tagEnlace*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // tagFinBoton ::= menor finBoton mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(37/*tagFinBoton*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // tagBoton ::= menor boton mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(36/*tagBoton*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // tagBoton ::= menor boton listaPropiedadBoton mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(36/*tagBoton*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // tagFinImagen ::= menor finImagen mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(35/*tagFinImagen*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // tagImagen ::= menor imagen listaPropiedadeesCajaOpciones mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(34/*tagImagen*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // tagImagen ::= menor imagen mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(34/*tagImagen*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // tagFinPanel ::= menor finPanel mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(59/*tagFinPanel*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // tagPanel ::= menor panel listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(58/*tagPanel*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // tagPanel ::= menor panel mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(58/*tagPanel*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // tagFinTexto ::= menor finTexto mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(33/*tagFinTexto*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // tagTexto ::= menor texto listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(32/*tagTexto*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // tagTexto ::= menor texto mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(32/*tagTexto*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // tagTitulo ::= menor finTitulo mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(28/*tagTitulo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // tagTitulo ::= menor titulo listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(28/*tagTitulo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // tagTitulo ::= menor titulo mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(28/*tagTitulo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // tagFinCuerpo ::= menor finCuerpo mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(31/*tagFinCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // tagCuerpo ::= menor cuerpo listaPropiedadesCuerpo mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(30/*tagCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // tagCuerpo ::= menor cuerpo mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(30/*tagCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // tagFinCcss ::= menor finCcss mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(27/*tagFinCcss*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // tagCcss ::= menor ccss rutaPropiedad mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(26/*tagCcss*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // tagCcss ::= menor ccss mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(26/*tagCcss*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // tagFinCjs ::= menor finCjs mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(25/*tagFinCjs*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // tagCjs ::= menor cjs rutaPropiedad mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(24/*tagCjs*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // tagCjs ::= menor cjs mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(24/*tagCjs*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // tagFil_t ::= menor fil_t mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(46/*tagFil_t*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // tagFil_t ::= menor fil_t listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(46/*tagFil_t*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // tagFinCb ::= menor finCb mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(45/*tagFinCb*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // tagCb ::= menor cb listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(44/*tagCb*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // tagCb ::= menor cb mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(44/*tagCb*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // tagFinCt ::= menor finCt mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(43/*tagFinCt*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // tagCt ::= menor ct listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(42/*tagCt*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // tagCt ::= menor ct mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(42/*tagCt*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // tagFinTabla ::= menor finTabla mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(41/*tagFinTabla*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // tagTabla ::= menor tabla listaPropiedadesGenerales mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(40/*tagTabla*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // tagTabla ::= menor tabla mayor 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(40/*tagTabla*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // listaPropiedadesCuerpo ::= listaPropiedadesCuerpo propiedadCuerpo 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(63/*listaPropiedadesCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // listaPropiedadesCuerpo ::= propiedadCuerpo 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(63/*listaPropiedadesCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // propiedadCuerpo ::= fondoPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(62/*propiedadCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // propiedadCuerpo ::= propiedadGeneral 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(62/*propiedadCuerpo*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // listaPropiedadBoton ::= propiedadBoton 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(61/*listaPropiedadBoton*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // listaPropiedadBoton ::= listaPropiedadBoton propiedadBoton 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(61/*listaPropiedadBoton*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // propiedadBoton ::= rutaPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(66/*propiedadBoton*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // propiedadBoton ::= clickPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(66/*propiedadBoton*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // propiedadBoton ::= propiedadGeneral 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(66/*propiedadBoton*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // listaPropiedadesEnlace ::= propiedadEnlace 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(65/*listaPropiedadesEnlace*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // listaPropiedadesEnlace ::= listaPropiedadesEnlace propiedadEnlace 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(65/*listaPropiedadesEnlace*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // propiedadEnlace ::= clickPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(70/*propiedadEnlace*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // propiedadEnlace ::= propiedadGeneral 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(70/*propiedadEnlace*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // listaPropiedadeesCajaOpciones ::= propiedadCajaOpciones 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(64/*listaPropiedadeesCajaOpciones*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // listaPropiedadeesCajaOpciones ::= listaPropiedadeesCajaOpciones propiedadCajaOpciones 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(64/*listaPropiedadeesCajaOpciones*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // propiedadCajaOpciones ::= clickPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(67/*propiedadCajaOpciones*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // propiedadCajaOpciones ::= propiedadGeneral 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(67/*propiedadCajaOpciones*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // listaPropiedadesOpcion ::= propiedadOpcion 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(69/*listaPropiedadesOpcion*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // listaPropiedadesOpcion ::= listaPropiedadesOpcion propiedadOpcion 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(69/*listaPropiedadesOpcion*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // propiedadOpcion ::= valorPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(68/*propiedadOpcion*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // propiedadOpcion ::= propiedadGeneral 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(68/*propiedadOpcion*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // listaPropiedadesGenerales ::= propiedadGeneral 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(19/*listaPropiedadesGenerales*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // listaPropiedadesGenerales ::= listaPropiedadesGenerales propiedadGeneral 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(19/*listaPropiedadesGenerales*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // propiedadGeneral ::= alineadoPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(18/*propiedadGeneral*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // propiedadGeneral ::= anchoPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(18/*propiedadGeneral*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // propiedadGeneral ::= altoPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(18/*propiedadGeneral*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // propiedadGeneral ::= grupoPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(18/*propiedadGeneral*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // propiedadGeneral ::= idPropiedad 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(18/*propiedadGeneral*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // alineadoPropiedad ::= alineado igualSimb cadena puntoComaSimb 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(12/*alineadoPropiedad*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // anchoPropiedad ::= ancho igualSimb cadena puntoComaSimb 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(11/*anchoPropiedad*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // altoPropiedad ::= alto igualSimb cadena puntoComaSimb 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(10/*altoPropiedad*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // grupoPropiedad ::= grupo igualSimb cadena puntoComaSimb 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(9/*grupoPropiedad*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // idPropiedad ::= id igualSimb cadena puntoComaSimb 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(8/*idPropiedad*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // valorPropiedad ::= valor igualSimb cadena puntoComaSimb 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(17/*valorPropiedad*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // fondoPropiedad ::= fondo igualSimb cadena puntoComaSimb 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(16/*fondoPropiedad*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // clickPropiedad ::= click igualSimb cadena puntoComaSimb 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(15/*clickPropiedad*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // rutaPropiedad ::= ruta igualSimb cadena puntoComaSimb 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(14/*rutaPropiedad*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= CHTML 
            {
              Object RESULT = null;

              CUP$Parser$result = new java_cup.runtime.Symbol(1/*INICIO*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

