
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 11 14:21:16 CST 2018
//----------------------------------------------------

package proyecto1_201122872.AnalizadorCHTML;

/** CUP generated class containing symbol constants. */
public class simbolosCHTML {
  /* terminals */
  public static final int ancho = 48;
  public static final int finCuerpo = 13;
  public static final int finSpinner = 43;
  public static final int finPanel = 17;
  public static final int fondo = 53;
  public static final int imagen = 20;
  public static final int finOpcion = 41;
  public static final int finEnlace = 25;
  public static final int derecha = 55;
  public static final int finTitulo = 15;
  public static final int finTabla = 27;
  public static final int finChtml = 5;
  public static final int finFil_t = 29;
  public static final int identificador = 59;
  public static final int caja_texto = 36;
  public static final int saltoFin = 44;
  public static final int finEncabezado = 7;
  public static final int alto = 47;
  public static final int texto_a = 34;
  public static final int panel = 16;
  public static final int grupo = 46;
  public static final int alineado = 49;
  public static final int finCt = 33;
  public static final int ruta = 52;
  public static final int numero = 61;
  public static final int ccss = 10;
  public static final int tabla = 26;
  public static final int chtml = 4;
  public static final int fil_t = 28;
  public static final int menor = 2;
  public static final int ct = 32;
  public static final int EOF = 0;
  public static final int puntoComaSimb = 58;
  public static final int finCjs = 9;
  public static final int error = 1;
  public static final int mayor = 3;
  public static final int finImagen = 21;
  public static final int finCb = 31;
  public static final int finTexto = 19;
  public static final int valor = 50;
  public static final int cuerpo = 12;
  public static final int spinner = 42;
  public static final int finCcss = 11;
  public static final int click = 51;
  public static final int cb = 30;
  public static final int id = 45;
  public static final int finCaja_texto = 37;
  public static final int finBoton = 23;
  public static final int opcion = 40;
  public static final int cjs = 8;
  public static final int finTexto_a = 35;
  public static final int enlace = 24;
  public static final int centrado = 56;
  public static final int titulo = 14;
  public static final int caja = 38;
  public static final int encabezado = 6;
  public static final int texto = 18;
  public static final int izquierda = 54;
  public static final int igualSimb = 57;
  public static final int boton = 22;
  public static final int cadena = 60;
  public static final int finCaja = 39;
}

