
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 01 20:55:40 CST 2018
//----------------------------------------------------

package proyecto1_201122872.AnalizadorCHTML;

/** CUP generated class containing symbol constants. */
public class simbolosCHTML {
  /* terminals */
  public static final int ancho = 49;
  public static final int finCuerpo = 14;
  public static final int finSpinner = 44;
  public static final int finPanel = 18;
  public static final int fondo = 54;
  public static final int imagen = 21;
  public static final int finOpcion = 42;
  public static final int finEnlace = 26;
  public static final int derecha = 56;
  public static final int finTitulo = 16;
  public static final int finTabla = 28;
  public static final int finChtml = 6;
  public static final int finFil_t = 30;
  public static final int identificador = 60;
  public static final int caja_texto = 37;
  public static final int saltoFin = 45;
  public static final int finEncabezado = 8;
  public static final int alto = 48;
  public static final int texto_a = 35;
  public static final int panel = 17;
  public static final int grupo = 47;
  public static final int alineado = 50;
  public static final int finCt = 34;
  public static final int ruta = 53;
  public static final int numero = 62;
  public static final int ccss = 11;
  public static final int tabla = 27;
  public static final int chtml = 5;
  public static final int fil_t = 29;
  public static final int menor = 2;
  public static final int ct = 33;
  public static final int EOF = 0;
  public static final int cadena2 = 4;
  public static final int puntoComaSimb = 59;
  public static final int finCjs = 10;
  public static final int error = 1;
  public static final int mayor = 3;
  public static final int finImagen = 22;
  public static final int finCb = 32;
  public static final int finTexto = 20;
  public static final int valor = 51;
  public static final int cuerpo = 13;
  public static final int spinner = 43;
  public static final int finCcss = 12;
  public static final int click = 52;
  public static final int cb = 31;
  public static final int id = 46;
  public static final int finCaja_texto = 38;
  public static final int finBoton = 24;
  public static final int opcion = 41;
  public static final int cjs = 9;
  public static final int finTexto_a = 36;
  public static final int enlace = 25;
  public static final int centrado = 57;
  public static final int titulo = 15;
  public static final int caja = 39;
  public static final int encabezado = 7;
  public static final int texto = 19;
  public static final int izquierda = 55;
  public static final int igualSimb = 58;
  public static final int boton = 23;
  public static final int cadena = 61;
  public static final int finCaja = 40;
}

