
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 08 14:44:52 CST 2018
//----------------------------------------------------

package proyecto1_201122872.AnalizadorCSS;

/** CUP generated class containing symbol constants. */
public class simbolosCSS {
  /* terminals */
  public static final int corCierra = 27;
  public static final int mayuscula = 24;
  public static final int opaque = 16;
  public static final int dosPuntos = 31;
  public static final int negrilla = 21;
  public static final int coma = 33;
  public static final int derecha = 18;
  public static final int igual = 28;
  public static final int multiplicacion = 36;
  public static final int letra = 7;
  public static final int capitalT = 25;
  public static final int autoredimension = 11;
  public static final int grupo = 3;
  public static final int alineado = 4;
  public static final int corAbre = 26;
  public static final int tamtex = 8;
  public static final int numero = 41;
  public static final int justificado = 20;
  public static final int vertical = 13;
  public static final int menos = 35;
  public static final int visible = 14;
  public static final int EOF = 0;
  public static final int mas = 34;
  public static final int verdadero = 38;
  public static final int error = 1;
  public static final int fondoelemento = 10;
  public static final int horizontal = 12;
  public static final int minuscula = 23;
  public static final int id = 42;
  public static final int puntoComa = 32;
  public static final int falso = 39;
  public static final int colortext = 9;
  public static final int centrado = 19;
  public static final int texto = 5;
  public static final int idTerminal = 2;
  public static final int izquierda = 17;
  public static final int booleano = 43;
  public static final int formato = 6;
  public static final int borde = 15;
  public static final int division = 37;
  public static final int cursiva = 22;
  public static final int abrePar = 29;
  public static final int cadena = 40;
  public static final int cierraPar = 30;
}

